server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
    #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
kaptcha:
  producer:
    image-width: 125
    image-height: 45
    text-producer-char-length: 4
    text-producer-font-size: 32
    text-producer-font-color: black
    noise-impl: com.google.code.kaptcha.impl.DefaultNoise
    border: no
