spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/lost?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root


  #图片上传大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB



server:
  port: 8080


mybatis-plus:
  configuration:
    # 自动转驼峰
    map-underscore-to-camel-case: true
    # 开启mysql语句日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    banner: false
